redactions = ["*_TOKEN", "*_SECRET", "*_KEY", "*_PASSWORD"]

[settings]
experimental = true
lockfile = true
env_shell_expand = true
idiomatic_version_file_enable_tools = ["rust"]
rust.cargo_home = ".cache/native/cargo"
rust.rustup_home = ".cache/native/rustup"

[tools]
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
"github:aya-rs/bpf-linker" = "latest"
hk = "latest"
pkl = "latest"
hadolint = "latest"
shellcheck = "latest"
"cargo:cargo-sort" = "latest"
"aqua:tamasfe/taplo" = "latest"
"github:casualjim/remark" = "latest"
gum = "latest"
lychee = "latest"
node = "lts"
cmake = "latest"
cargo-dist = "latest"

[[tools.rust]]
version = "stable"
profile = "default"
components = "llvm-tools,rust-analyzer,rust-src"
targets = "aarch64-apple-darwin,wasm32-unknown-unknown,wasm32-wasip2"

[[tools.rust]]
version = "nightly"
components = "llvm-tools,rustfmt,rust-src"

[env]
CARGO_TERM_COLOR = "always"
CARGO_HOME = "{{config_root}}/.cache/native/cargo"
RUSTUP_HOME = "{{config_root}}/.cache/native/rustup"
RUSTUP_TOOLCHAIN = "stable"
