#!/usr/bin/env bash

#MISE description="Run the Rust tests for this project"
#MISE sources=["Cargo.toml", "src/**/*.rs"]

proj_dir=$(git rev-parse --show-toplevel)
cd "$proj_dir" || exit 1

set -euo pipefail

cargo nextest run --cargo-quiet --workspace --show-progress=bar --status-level=slow "$@"
cargo nextest run --cargo-quiet --show-progress=bar --status-level=slow "$@"
