#!/usr/bin/env bash

#MISE description="Run the Rust tests for this project"
#MISE sources=["Cargo.toml", "src/**/*.rs", "crates/**/*.rs", "rules/**/*.toml"]

proj_dir=$(jj root 2>/dev/null || git rev-parse --show-toplevel)
cd "$proj_dir" || exit 1

set -euo pipefail

cargo nextest run --cargo-quiet --workspace --exclude hodor-ebpf-programs --show-progress=bar --status-level=slow "$@"
