//! Shared machinery for the structural `file_rewrite` adapters: one result
//! type, one state writer, and the format dispatch the adapters plug into.
//! Kubeconfig and talosconfig are the same idea — a tool's config file is a
//! rule stated in another shape — so they share everything except parsing.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
#[cfg(unix)]
use std::fs::Permissions;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use base64::{Engine as _, engine::general_purpose::STANDARD};
use hodor_config::config::{HostTlsCfg, RewriteFormat};
use serde::Serialize;

use crate::error::Error;
use crate::stack::workspace_slug;

/// Container path the grant layer mounts at in the hodor service. Fragments
/// name blobs under it; host and container serve resolve the same entries
/// because the state dir mounts there.
pub(crate) const GRANTS_STATE_DIR: &str = "/hodor/grants";

/// A tool config rewrite mapped onto its grant fragment and decoy twin.
#[derive(Debug)]
pub(crate) struct RewriteAdapted {
  /// Grant fragment TOML, holding the real credential.
  pub(crate) fragment: String,
  /// Decoy config for the agent: same endpoints, hodor CA, guest pair.
  pub(crate) decoy: String,
  /// Blobs to write beside the fragment: `(file name, bytes)`.
  pub(crate) materialized: Vec<(String, Vec<u8>)>,
}

/// A derived rule, minus the label: what both adapters hand the TOML
/// serializer. Serialization escapes every string the way TOML requires, so
/// no hand-rolled escaping exists anywhere on this path.
#[derive(Debug, Serialize)]
pub(crate) struct GrantFragment {
  /// Env name the rule resolves from.
  pub(crate) env: String,
  /// Registry-supplied shapes do not apply to derived rules.
  pub(crate) registry: bool,
  /// Allow entries the derived rule grants.
  pub(crate) allow: Vec<String>,
  /// Real credential, held inline.
  pub(crate) value: String,
  /// Per-entry TLS identity.
  pub(crate) tls: BTreeMap<String, HostTlsCfg>,
}

/// Serialize one grant fragment under `[rules.{label}]`, with the generation
/// header. Serialization cannot fail: every key and value is a string.
#[must_use]
pub(crate) fn render_fragment(source: &Path, label: &str, fragment: &GrantFragment) -> String {
  #[derive(Serialize)]
  struct Rules<'a> {
    rules: BTreeMap<&'a str, &'a GrantFragment>,
  }
  let rules = Rules {
    rules: BTreeMap::from([(label, fragment)]),
  };
  format!(
    "# generated by `hodor init` from {} — do not edit or commit: it holds the REAL credential.\n# Regenerated when the workspace config changes.\n{}",
    source.display(),
    toml::to_string_pretty(&rules).expect("string-only document always serializes"),
  )
}

/// Serialize the agent's decoy document with its generation header.
/// Serialization cannot fail: every value is a string, sequence, or mapping.
#[must_use]
pub(crate) fn render_decoy<D: Serialize>(doc: &D) -> String {
  format!(
    "# generated by `hodor init` — decoys only, safe to inspect.\n{}",
    serde_yaml::to_string(doc).expect("string-only document always serializes"),
  )
}

/// The format an unstated rewrite probes as, if any. Kubeconfig first: its
/// markers are the more specific pair.
#[must_use]
pub(crate) fn sniff(content: &[u8]) -> Option<RewriteFormat> {
  let text = String::from_utf8_lossy(content);
  if text.contains("current-context:") && text.contains("clusters:") {
    return Some(RewriteFormat::Kubeconfig);
  }
  if text.contains("contexts:") && text.contains("endpoints:") {
    return Some(RewriteFormat::Talos);
  }
  None
}

/// Decode an optional base64 blob, erroring when the field is malformed.
///
/// # Errors
///
/// Returns [`Error::RewriteInvalid`] naming the file, format, and field.
pub(crate) fn decode(file: &Path, format: RewriteFormat, data: Option<&str>, field: &str) -> Result<Option<Vec<u8>>, Error> {
  data
    .filter(|data| !data.is_empty())
    .map(|data| {
      STANDARD.decode(data.trim()).map_err(|_| Error::RewriteInvalid {
        file: file.to_path_buf(),
        format,
        detail: format!("field `{field}` is not valid base64"),
      })
    })
    .transpose()
}

/// Grant label from the source path and a distinguishing name:
/// `{path-slug}-{file-stem}-{name}`.
///
/// # Errors
///
/// Returns [`Error::RewriteInvalid`] when the path or name sluggifies to
/// nothing.
pub(crate) fn rewrite_label(source: &Path, format: RewriteFormat, name: &str) -> Result<String, Error> {
  let invalid = |detail: String| Error::RewriteInvalid {
    file: source.to_path_buf(),
    format,
    detail,
  };
  let parent = source.parent().ok_or_else(|| invalid("has no parent directory".to_string()))?;
  let stem = source
    .file_stem()
    .map(|stem| stem.to_string_lossy())
    .ok_or_else(|| invalid("has no file name".to_string()))?;
  let path_slug = workspace_slug(parent);
  let slug = |text: &str| {
    let cleaned: String = text
      .to_lowercase()
      .chars()
      .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
      .collect();
    cleaned.trim_matches('-').to_string()
  };
  if path_slug.is_empty() || slug(&stem).is_empty() || slug(name).is_empty() {
    return Err(invalid("path or context sluggifies to nothing".to_string()));
  }
  Ok(format!("{}-{}-{}", path_slug, slug(&stem), slug(name)))
}

/// Write the grant layer: the grant fragments concatenated into the marker
/// global config, plus the blobs under `rules.d`, pruning stale adapter blobs
/// so a removed rewrite stops granting. The hodor service points
/// `HODOR_CONFIG` at the marker, adding this layer without touching user
/// config.
///
/// # Errors
///
/// Returns an error when the directory, the marker, or a blob cannot be
/// written, or when a stale file cannot be pruned.
pub(crate) fn write_state(state_dir: &Path, adapted: &[RewriteAdapted]) -> Result<(), Error> {
  let marker = state_dir.join("hodor.toml");
  let rules_dir = state_dir.join("rules.d");
  if adapted.is_empty() && !marker.is_file() {
    return Ok(());
  }
  fs::create_dir_all(&rules_dir).map_err(|source| Error::CreateDir {
    path: rules_dir.clone(),
    source,
  })?;
  let mut toml = String::from("# generated by `hodor init`: tool-config grant layer. `HODOR_CONFIG` points here in the hodor service.\n");
  let mut current = BTreeSet::new();
  for grant in adapted {
    toml.push_str(&grant.fragment);
    for (name, bytes) in &grant.materialized {
      write_secret(&rules_dir.join(name), bytes)?;
      current.insert(name.clone());
    }
  }
  write_secret(&marker, toml.as_bytes())?;
  for entry in fs::read_dir(&rules_dir).map_err(|source| Error::ReadFile {
    path: rules_dir.clone(),
    source,
  })? {
    let path = entry
      .map_err(|source| Error::ReadFile {
        path: rules_dir.clone(),
        source,
      })?
      .path();
    let stale = |name: &str| (name.starts_with("kube-") || name.starts_with("talos-")) && !current.contains(name);
    if path.is_file() && path.file_name().is_some_and(|name| stale(&name.to_string_lossy())) {
      fs::remove_file(&path).map_err(|source| Error::RemoveFile {
        path: path.clone(),
        source,
      })?;
    }
  }
  Ok(())
}

/// Write a secret file the agent must never see: owner-only on unix.
pub(crate) fn write_secret(path: &Path, bytes: &[u8]) -> Result<(), Error> {
  fs::write(path, bytes).map_err(|source| Error::WriteFile {
    path: path.to_path_buf(),
    source,
  })?;
  #[cfg(unix)]
  fs::set_permissions(path, Permissions::from_mode(0o600)).map_err(|source| Error::WriteFile {
    path: path.to_path_buf(),
    source,
  })?;
  Ok(())
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn sniff_picks_kubeconfig_over_talos_on_shared_markers() {
    assert_eq!(
      sniff(b"context: c\ncontexts:\n  c:\n    endpoints:\n      - 10.0.0.1\n"),
      Some(RewriteFormat::Talos)
    );
    assert_eq!(
      sniff(b"current-context: c\nclusters:\n- name: c\n"),
      Some(RewriteFormat::Kubeconfig)
    );
    assert_eq!(sniff(b"just a file\n"), None);
  }

  #[test]
  fn write_state_prunes_stale_kube_and_talos_blobs() {
    let dir = tempfile::tempdir().unwrap();
    let state = dir.path().join("grants");
    let adapted = RewriteAdapted {
      fragment: "[rules.x]\n".to_string(),
      decoy: String::new(),
      materialized: vec![("kube-a.crt".to_string(), b"a".to_vec())],
    };
    write_state(&state, &[adapted]).unwrap();
    let rules = state.join("rules.d");
    let stale_talos = rules.join("talos-old.crt");
    let stale_other = rules.join("other.crt");
    fs::write(&stale_talos, "stale").unwrap();
    fs::write(&stale_other, "stale").unwrap();
    write_state(&state, &[]).unwrap();
    assert!(!stale_talos.exists(), "removed talos rewrites stop granting");
    assert!(stale_other.exists(), "non-adapter blobs are untouched");
  }
}
