//! jj config adapter for `file_rewrite`: jj's own configuration holds no
//! credentials — authentication rides git — so the adapter's job is the
//! agent's decoy twin: the user chain resolved the way jj resolves it,
//! re-serialized as one TOML document, with the commit identity jj would
//! otherwise fall back to git config for filled in at generation time
//! (the container has no `~/.gitconfig` to fall back to unless a `git`
//! rewrite is declared too).
//!
//! Resolution order, from jj's documentation: `JJ_CONFIG` (a file, a
//! directory of `*.toml`, or a platform-separated list; set even to the
//! empty string it replaces the default locations), else `$HOME/.jjconfig.toml`,
//! then the platform config `<config-dir>/jj/config.toml`, then
//! `<config-dir>/jj/conf.d/*.toml` in lexicographic order. Repo and
//! workspace config stay in the mounted workspace and are not part of the
//! twin. System config stays behind; containers carry none.

use std::fs;
use std::path::{Path, PathBuf};

use toml::Table;
use toml::Value;

use crate::adapt::RewriteAdapted;
use crate::git::{self, text};

/// The platform user-config path: the anchor for error messages and the
/// path a declared rewrite is compared against.
pub(crate) fn config_path() -> PathBuf {
  dirs::config_dir().map_or_else(PathBuf::new, |dir| dir.join("jj").join("config.toml"))
}
/// The chain paths in load order, for the declared-rewrite comparison.
pub(crate) fn chain_paths() -> Vec<PathBuf> {
  user_chain()
}

/// Map jj's resolved user configuration onto the agent's decoy twin,
/// credential paths for `jj git` are git's, covered by the `git` and `ssh`
/// adapters. The anchor for messages is the first chain file that exists,
/// so warnings name what jj actually reads. A chain file that does not
/// parse skips the whole source with a warning rather than failing.
pub(crate) fn adapt(root: &Path) -> Option<RewriteAdapted> {
  let chain = user_chain();
  let anchor = chain.iter().find(|path| path.is_file()).map_or_else(config_path, Clone::clone);
  let mut merged = Table::new();
  let mut present = false;
  for path in &chain {
    let text = match fs::read_to_string(path) {
      Ok(text) => text,
      Err(_) => continue,
    };
    present = true;
    let parsed = match toml::from_str::<Table>(&text) {
      Ok(parsed) => parsed,
      Err(err) => {
        tracing::warn!(file = %path.display(), %err, "jj source skipped: the file does not parse");
        return None;
      }
    };
    merge_table(&mut merged, parsed);
  }
  if !present {
    return None;
  }
  fill_git_identity(&mut merged, root);
  let decoy = match toml::to_string_pretty(&Value::Table(merged)) {
    Ok(decoy) => decoy,
    Err(err) => {
      tracing::warn!(file = %anchor.display(), %err, "jj source skipped: the merged chain does not serialize");
      return None;
    }
  };
  Some(RewriteAdapted {
    fragment: String::new(),
    decoy: format!("# generated by `hodor init` — resolved from jj's user chain, safe to inspect.\n{decoy}"),
    materialized: Vec::new(),
    decoy_files: Vec::new(),
  })
}

/// The user configuration chain in jj's load order: `JJ_CONFIG` when set
/// (even empty, which yields nothing), else home, platform config, then the
/// platform `conf.d` directory in lexicographic order.
fn user_chain() -> Vec<PathBuf> {
  if let Ok(config) = std::env::var("JJ_CONFIG") {
    return config
      .split(':')
      .filter(|entry| !entry.is_empty())
      .flat_map(expand_chain_entry)
      .collect();
  }
  let mut chain = Vec::new();
  if let Some(home) = std::env::var_os("HOME") {
    chain.push(PathBuf::from(home).join(".jjconfig.toml"));
  }
  if let Some(config_dir) = dirs::config_dir() {
    chain.push(config_dir.join("jj").join("config.toml"));
    chain.extend(sorted_tomls(&config_dir.join("jj").join("conf.d")));
  }
  chain
}

/// One `JJ_CONFIG` entry: a file, or a directory of `*.toml` in
/// lexicographic order.
fn expand_chain_entry(entry: &str) -> Vec<PathBuf> {
  let path = PathBuf::from(entry);
  if path.is_dir() { sorted_tomls(&path) } else { vec![path] }
}

/// The `*.toml` files of one directory, in name order.
fn sorted_tomls(dir: &Path) -> Vec<PathBuf> {
  let mut files: Vec<PathBuf> = fs::read_dir(dir)
    .into_iter()
    .flatten()
    .filter_map(Result::ok)
    .map(|entry| entry.path())
    .filter(|path| path.is_file() && path.extension().is_some_and(|extension| extension == "toml"))
    .collect();
  files.sort();
  files
}

/// Layer one file's table over the merged chain: tables merge per key,
/// every other value from the later file wins.
fn merge_table(base: &mut Table, over: Table) {
  for (key, value) in over {
    match (base.remove(&key), value) {
      (Some(Value::Table(mut nested)), Value::Table(over)) => {
        merge_table(&mut nested, over);
        base.insert(key, Value::Table(nested));
      }
      (_, value) => {
        base.insert(key, value);
      }
    }
  }
}

/// Fill `user.name`/`user.email` from the resolved git chain when the jj
/// chain states neither — jj's own fallback, applied at generation time
/// because the container has no gitconfig to fall back to.
fn fill_git_identity(merged: &mut Table, root: &Path) {
  let Ok(Some(config)) = git::resolve(root) else {
    return;
  };
  let name = config.string_by("user", None, "name").map(|value| text(&value));
  let email = config.string_by("user", None, "email").map(|value| text(&value));
  if name.is_none() && email.is_none() {
    return;
  }
  let user = merged.entry("user").or_insert_with(|| Value::Table(Table::new()));
  let Value::Table(user) = user else {
    return;
  };
  for (key, value) in [("name", name), ("email", email)] {
    if !user.contains_key(key)
      && let Some(value) = value
    {
      user.insert(key.to_string(), Value::String(value));
    }
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use std::env;
  use std::ffi::OsString;
  use std::sync::{Mutex, MutexGuard, PoisonError};

  static ENV_LOCK: Mutex<()> = Mutex::new(());

  fn lock_env() -> MutexGuard<'static, ()> {
    ENV_LOCK.lock().unwrap_or_else(PoisonError::into_inner)
  }

  /// Pin jj's and git's resolution to fixtures.
  fn env<T>(home: &Path, xdg: &Path, git_global: &Path, jj_config: Option<&str>, test: impl FnOnce() -> T) -> T {
    let _guard = lock_env();
    let names = ["HOME", "XDG_CONFIG_HOME", "JJ_CONFIG", "GIT_CONFIG_GLOBAL", "GIT_CONFIG_NOSYSTEM"];
    let saved: Vec<(String, Option<OsString>)> = names.into_iter().map(|name| (name.to_string(), env::var_os(name))).collect();
    // SAFETY: test-only mutation, serialized by ENV_LOCK.
    unsafe {
      env::set_var("HOME", home);
      env::set_var("XDG_CONFIG_HOME", xdg);
      env::set_var("GIT_CONFIG_GLOBAL", git_global);
      env::set_var("GIT_CONFIG_NOSYSTEM", "1");
      match jj_config {
        Some(value) => env::set_var("JJ_CONFIG", value),
        None => env::remove_var("JJ_CONFIG"),
      }
    }
    let result = test();
    for (name, value) in saved {
      // SAFETY: test-only mutation, serialized by ENV_LOCK.
      unsafe {
        match value {
          Some(value) => env::set_var(&name, value),
          None => env::remove_var(&name),
        }
      }
    }
    result
  }

  fn git_repo(dir: &Path, local: &str) {
    let git = dir.join(".git");
    fs::create_dir_all(git.join("objects")).unwrap();
    fs::create_dir_all(git.join("refs").join("heads")).unwrap();
    fs::write(git.join("HEAD"), b"ref: refs/heads/main\n").unwrap();
    fs::write(
      git.join("refs").join("heads").join("main"),
      b"1111111111111111111111111111111111111111\n",
    )
    .unwrap();
    fs::write(git.join("config"), local).unwrap();
  }

  #[test]
  fn later_chain_files_win_and_git_identity_falls_back() {
    let home = tempfile::tempdir().unwrap();
    fs::write(home.path().join(".jjconfig.toml"), "[user]\nname = 'Home Name'\n").unwrap();
    let xdg = tempfile::tempdir().unwrap();
    fs::create_dir_all(xdg.path().join("jj")).unwrap();
    fs::write(
      xdg.path().join("jj").join("config.toml"),
      "[user]\nemail = 'platform@mail'\n[ui]\ndefault-command = 'log'\n",
    )
    .unwrap();
    let git_home = tempfile::tempdir().unwrap();
    let git_global = git_home.path().join("gitconfig");
    fs::write(&git_global, "[user]\n\tname = Git Name\n\temail = git@mail\n").unwrap();
    let work = tempfile::tempdir().unwrap();
    git_repo(work.path(), "");
    let twin = env(home.path(), xdg.path(), &git_global, None, || {
      adapt(work.path()).expect("user chain present")
    })
    .decoy;
    let parsed: Value = toml::from_str(&twin[twin.find('[').unwrap()..]).unwrap();
    let user = parsed.get("user").unwrap();
    assert_eq!(
      user.get("name").and_then(Value::as_str),
      Some("Home Name"),
      "jj's own name wins over the git fallback: {twin}"
    );
    assert_eq!(user.get("email").and_then(Value::as_str), Some("platform@mail"), "{twin}");
    assert!(twin.contains("default-command"), "{twin}");
    assert!(
      !twin.contains("Git Name"),
      "the git fallback does not override a stated name: {twin}"
    );
  }

  #[test]
  fn git_identity_fills_a_missing_user() {
    let home = tempfile::tempdir().unwrap();
    let xdg = tempfile::tempdir().unwrap();
    fs::create_dir_all(xdg.path().join("jj")).unwrap();
    fs::write(xdg.path().join("jj").join("config.toml"), "[ui]\ncolor = 'never'\n").unwrap();
    let git_home = tempfile::tempdir().unwrap();
    let git_global = git_home.path().join("gitconfig");
    fs::write(&git_global, "[user]\n\tname = Git Name\n\temail = git@mail\n").unwrap();
    let work = tempfile::tempdir().unwrap();
    git_repo(work.path(), "");
    let twin = env(home.path(), xdg.path(), &git_global, None, || {
      adapt(work.path()).expect("user chain present")
    })
    .decoy;
    assert!(twin.contains("Git Name"), "{twin}");
    assert!(twin.contains("git@mail"), "{twin}");
    assert!(twin.contains("color = \"never\""), "the chain travels verbatim: {twin}");
  }

  #[test]
  fn jj_config_env_replaces_the_default_chain() {
    let home = tempfile::tempdir().unwrap();
    let xdg = tempfile::tempdir().unwrap();
    fs::create_dir_all(xdg.path().join("jj")).unwrap();
    fs::write(xdg.path().join("jj").join("config.toml"), "[ui]\ndefault-command = 'log'\n").unwrap();
    fs::write(home.path().join(".jjconfig.toml"), "[user]\nname = 'Home Name'\n").unwrap();
    let only = tempfile::tempdir().unwrap();
    let only_file = only.path().join("only.toml");
    fs::write(&only_file, "[template-aliases]\n'commit_id.short()' = 'commit_id.short(8)'\n").unwrap();
    let git_home = tempfile::tempdir().unwrap();
    let git_global = git_home.path().join("gitconfig");
    fs::write(&git_global, "").unwrap();
    let work = tempfile::tempdir().unwrap();
    git_repo(work.path(), "");
    let twin = env(home.path(), xdg.path(), &git_global, only_file.to_str(), || {
      adapt(work.path()).expect("user chain present")
    })
    .decoy;
    assert!(twin.contains("template-aliases"), "{twin}");
    assert!(
      !twin.contains("default-command"),
      "JJ_CONFIG replaces the default locations: {twin}"
    );
    assert!(!twin.contains("Home Name"), "{twin}");
  }
}
