//! Compose stack generation: decoy selection, mount resolution, and YAML.

use std::cmp::Reverse;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Component, Path, PathBuf};

use dirs::{config_dir as dirs_config_dir, home_dir, state_dir};
use hodor_config::cli::{Cli, ProxyBackend};
use hodor_config::config::{
  AppConfig, FileRewrite, HostTlsCfg, RewriteFormat, RuleCfg, SHARED_PROFILE, ToolCfg, config_dir, load, project_config_file,
  project_config_write_path, project_rules_dir, rules_dir, valid_profile,
};
use hodor_config::grants::GuestTlsMode;
use hodor_config::registry::Registry;
use hodor_fnox::{FNOX_ENV, FnoxSource, selected_envs};
use hodor_pki::ca::{CertAuthority, load_or_generate, load_or_generate_client_pair};
use libc::getuid;
use xpanda::Xpanda;

use crate::adapt::{self, GRANTS_STATE_DIR, RewriteAdapted, sniff};
use crate::error::Error;
use crate::expand::{apply_rewrites, block_on, build_expander, expand_path, expand_value, resolution_env, rewrite_file_name};
use crate::kube;
use crate::paths::{Mount, covering, expand, translate};
use crate::ssh;
use crate::talos;

/// Revision of the generated stack's shape. Bump whenever what
/// [`Stack::render`] emits changes in a way an existing stack must pick up —
/// a new service, new publishings, an environment variable the wiring needs —
/// so a stack generated by an older binary regenerates on the next `hodor
/// init` or `hodor agent`, exactly like one generated from an older config;
/// the bundled command never leaves the old wiring behind. Shape 2 adds the
/// `fwd` exposure sidecar, `[workspace] ports`, and `HODOR_LISTEN`. Shape 3
/// mounts profiles instead of agent directories, and adds `[workspace]
/// passthrough` interpolation and `file_rewrite` mounts. Shape 4 mounts the
/// tool-config grant layer at `/hodor/grants` instead of `/hodor/kube`. Shape
/// 5 mounts the global `rules.d` into the hodor service, so in-container rule
/// derivation sees the same registry hosts as the host.
pub(crate) const STACK_SHAPE: u32 = 5;

/// The shape revision a generated stack carries, from its `# stack shape:`
/// marker line; `None` for a file without a readable one, which is a stack
/// from before the marker existed.
pub(crate) fn stack_shape_in(compose: &str) -> Option<u32> {
  compose
    .lines()
    .find_map(|line| line.trim_start().strip_prefix("# stack shape: "))
    .and_then(|shape| shape.trim().parse().ok())
}

/// One selected env var with its decoy value.
pub(crate) struct Decoy {
  /// Env var name as the rule declares it.
  pub env: String,
  /// Decoy value for the agent environment.
  pub value: String,
}

/// Select every fnox-declared name the registry knows, with its decoy.
pub(crate) fn select(fnox: Option<&FnoxSource>, registry: &Registry) -> Vec<Decoy> {
  selected_envs(fnox, registry)
    .into_iter()
    .map(|env| {
      let value = registry.decoy(&env, None);
      Decoy { env, value }
    })
    .collect()
}

/// Reshape a selection with each rule's own pattern. Serve-time substitution
/// derives its fake from `rule.pattern`, so a decoy built from the registry
/// default instead would never match and the swap would silently not happen.
pub(crate) fn with_rule_patterns(decoys: Vec<Decoy>, registry: &Registry, rules: &BTreeMap<String, RuleCfg>) -> Vec<Decoy> {
  decoys
    .into_iter()
    .map(|decoy| {
      let pattern = rules
        .values()
        .find(|rule| rule.env == decoy.env)
        .and_then(|rule| rule.pattern.as_deref());
      Decoy {
        value: registry.decoy(&decoy.env, pattern),
        ..decoy
      }
    })
    .collect()
}

/// Split a selection by whether the registry states hosts for the name.
/// Active rules come first, names with no endpoint second.
pub(crate) fn by_hosts(registry: &Registry, decoys: Vec<Decoy>) -> (Vec<Decoy>, Vec<Decoy>) {
  decoys
    .into_iter()
    .partition(|decoy| registry.lookup(&decoy.env).is_some_and(|known| !known.hosts.is_empty()))
}
/// Env names serve-time derivation turns into rules: fnox-declared,
/// registry-known, with hosts.
pub(crate) fn derivable_envs(fnox: Option<&FnoxSource>, registry: &Registry) -> Vec<String> {
  by_hosts(registry, select(fnox, registry))
    .0
    .into_iter()
    .map(|decoy| decoy.env)
    .collect()
}

/// A passthrough name that is also a rule env or a selected decoy is a
/// generation-time error: one name takes one path, never both.
///
/// # Errors
///
/// Returns an error naming the offending name when it overlaps.
pub(crate) fn validate_passthrough(rules: &BTreeMap<String, RuleCfg>, decoys: &[Decoy], passthrough: &[String]) -> Result<(), Error> {
  for name in passthrough {
    if rules.values().any(|rule| &rule.env == name) {
      return Err(Error::PassthroughOverlapRule { name: name.clone() });
    }
    if decoys.iter().any(|decoy| &decoy.env == name) {
      return Err(Error::PassthroughOverlapDecoy { name: name.clone() });
    }
  }
  Ok(())
}

/// fnox-declared names nothing covers, sorted: not registry-selected, not
/// passthrough, and not fnox's own provider wiring (which the proxy forwards
/// itself).
pub(crate) fn uncovered_names(declared: &BTreeSet<String>, selected: &[String], passthrough: &[String]) -> Vec<String> {
  declared
    .iter()
    .filter(|name| !selected.contains(name) && !passthrough.contains(name) && !FNOX_ENV.contains(&name.as_str()))
    .cloned()
    .collect()
}

/// One sorted warning naming uncovered names and the fix; `None` when every
/// declared name is covered.
pub(crate) fn uncovered_warning(names: &[String]) -> Option<String> {
  if names.is_empty() {
    return None;
  }
  let mut sorted = names.to_vec();
  sorted.sort();
  Some(format!(
    "warning: fnox declares {} with no rule or passthrough ({}); add [rules.*] entries or [workspace] passthrough names, or remove them from fnox if unused",
    if sorted.len() == 1 { "a secret" } else { "secrets" },
    sorted.join(", ")
  ))
}

/// `hodor rules`: env-only rules for the secrets this workspace can get, plus
/// a note naming the fnox declarations no registry entry covers. One
/// `[rules.<label>]` block per env var fnox declares that the registry knows
/// how to swap; `hodor init` writes the same blocks into a fresh workspace
/// config.
///
/// `root` adds the workspace's own `rules.d` overrides, so the printed rules
/// match the ones generation derives decoys from.
///
/// # Errors
///
/// Returns an error when the registry or the fnox source cannot be opened.
pub fn rules_command(root: Option<&Path>) -> Result<String, Error> {
  let registry = generation_registry(root)?;
  let fnox = open_fnox()?;
  let (with_hosts, hostless) = by_hosts(&registry, select(fnox.as_ref(), &registry));
  let known = selected_envs(fnox.as_ref(), &registry);
  let unknown = fnox
    .as_ref()
    .map(|fnox| {
      fnox
        .declared()
        .iter()
        .filter(|name| !known.contains(name))
        .cloned()
        .collect::<Vec<_>>()
    })
    .unwrap_or_default();
  Ok(rules_toml(&with_hosts, &hostless, &unknown))
}

/// Split a trailing `:ro` or `:rw` off an include entry; bare paths are rw.
pub(crate) fn split_mode(entry: &Path) -> (PathBuf, bool) {
  let text = entry.as_os_str().to_str().unwrap_or_default();
  if let Some(rest) = text.strip_suffix(":ro") {
    return (PathBuf::from(rest), true);
  }
  if let Some(rest) = text.strip_suffix(":rw") {
    return (PathBuf::from(rest), false);
  }
  (entry.to_path_buf(), false)
}

/// The agent-side mounts carrying each mtls rule's guest identity: one pair
/// minted per rule (`<guests-dir>/<label>.pem` plus `.key`, load-or-generate),
/// mounted read-only at the container paths the rule's entries declare, or
/// `{home}/.config/hodor/guest/<label>.pem` and `.key` when an entry states
/// none. Compose is a placement consumer only: hodor-proxy reads the mode, the
/// agent holds the identity files.
///
/// # Errors
///
/// Returns an error when a pair cannot be minted or written.
pub(crate) fn guest_identity_mounts(
  rules: &BTreeMap<String, RuleCfg>,
  ca: &CertAuthority,
  guests_dir: &Path,
  home: &str,
) -> Result<Vec<Mount>, Error> {
  let mut mounts = Vec::new();
  for (label, rule) in rules {
    let mtls: Vec<&HostTlsCfg> = rule.tls.values().filter(|tls| tls.guest_tls_mode == GuestTlsMode::Mtls).collect();
    if mtls.is_empty() {
      continue;
    }
    let (cert, key) = load_or_generate_client_pair(ca, guests_dir, label)?;
    for tls in mtls {
      let cert_container = tls
        .guest_cert
        .clone()
        .unwrap_or_else(|| PathBuf::from(format!("{home}/.config/hodor/guest/{label}.pem")));
      let key_container = tls
        .guest_key
        .clone()
        .unwrap_or_else(|| PathBuf::from(format!("{home}/.config/hodor/guest/{label}.key")));
      mounts.push(Mount {
        host: cert.clone(),
        container: cert_container,
        ro: true,
      });
      mounts.push(Mount {
        host: key.clone(),
        container: key_container,
        ro: true,
      });
    }
  }
  Ok(mounts)
}

/// Fixed port the generated stack renders as `HODOR_LISTEN` instead of the
/// `127.0.0.1:8080` default: the explicit proxy is loopback-bound in the
/// shared netns, and 8080 is the port dev servers default to — squatted on
/// by the proxy, an agent server could never bind its loopback listener and
/// the `fwd` sidecar would have nothing to expose.
pub(crate) const EXPLICIT_LISTEN: &str = "127.0.0.1:8099";

/// Generate the stack for a workspace directory: decoys for every
/// fnox-declared name the registry knows (same selection as `hodor rules`)
/// plus the translated mounts from `[workspace]`.
/// What the hodor service mounts and forwards so the container's fnox resolves
/// what the host's does: its config directory (identity, providers, config),
/// hodor's own fnox level.
#[derive(Default)]
pub(crate) struct FnoxBinds {
  pub(crate) mounts: Vec<Mount>,
}

/// The fnox config directory fnox itself resolves: `FNOX_CONFIG_DIR`, else
/// `<config-dir>/fnox`.
pub(crate) fn fnox_config_dir(host_home: Option<&Path>) -> Option<PathBuf> {
  if let Some(dir) = env::var_os("FNOX_CONFIG_DIR") {
    return Some(PathBuf::from(dir));
  }
  dirs_config_dir()
    .or_else(|| host_home.map(|home| home.join(".config")))
    .map(|dir| dir.join("fnox"))
}

/// Bind mounts and environment the hodor service needs to act like fnox does.
/// Every mount is conditional on the host path existing: docker turns a bind of
/// a missing path into a directory, which is never what we want. Container paths
/// are what fnox and hodor look at inside, where the home is `/root`.
pub(crate) fn fnox_binds(fnox_dir: Option<&Path>, config_dir: Option<&Path>) -> FnoxBinds {
  let mut binds = FnoxBinds { mounts: Vec::new() };
  if let Some(dir) = fnox_dir.filter(|dir| dir.is_dir()) {
    binds.mounts.push(Mount {
      host: dir.to_path_buf(),
      container: PathBuf::from("/root/.config/fnox"),
      ro: true,
    });
  }
  let mut levels = config_dir
    .and_then(|dir| std::fs::read_dir(dir).ok())
    .into_iter()
    .flatten()
    .flatten()
    .map(|entry| entry.path())
    .filter(|path| {
      path.is_file()
        && path.file_name().is_some_and(|name| {
          let name = name.to_string_lossy();
          name.starts_with("fnox") && name.ends_with(".toml")
        })
    })
    .collect::<Vec<_>>();
  levels.sort();
  for path in levels {
    binds.mounts.push(Mount {
      container: Path::new("/root/.config/hodor").join(path.file_name().unwrap_or_default()),
      host: path,
      ro: true,
    });
  }
  let rules_d = config_dir.map(|dir| dir.join("rules.d")).filter(|dir| dir.is_dir());
  if let Some(dir) = rules_d {
    binds.mounts.push(Mount {
      host: dir,
      container: PathBuf::from("/root/.config/hodor/rules.d"),
      ro: true,
    });
  }
  binds
}

/// Mount entries for the workspace root and `[workspace] include`, ordered the
/// way `covering` wants them: parents first, so a covering mount wins and
/// covered paths drop out. A path that is not there is an error rather than a
/// warning, because docker mounts an empty directory in its place.
pub(crate) fn include_entries(root: &Path, includes: &[PathBuf], host_home: Option<&Path>) -> Result<Vec<(PathBuf, bool)>, Error> {
  let mut entries = vec![(root.to_path_buf(), false)];
  for entry in includes {
    let (path, ro) = split_mode(entry);
    let host = expand(&path, root, host_home);
    if !host.exists() {
      return Err(Error::IncludeMissing { entry: entry.clone() });
    }
    entries.push((host, ro));
  }
  entries.sort_by_key(|(path, _)| Reverse(path.components().count()));
  Ok(entries)
}

pub(crate) fn generate_stack(root: &Path, backend: ProxyBackend, hodor_version: &str) -> Result<String, Error> {
  let registry = generation_registry(Some(root))?;
  let config = workspace_config(root)?;
  let raw_home = config.workspace.home.clone().ok_or_else(|| Error::HomeRequired {
    detail: "for stack generation".to_string(),
  })?;
  let fnox = open_fnox()?;
  let referenced = config.workspace.referenced_variables(&[raw_home.as_str()]);
  let env = block_on(resolution_env(&registry, fnox.as_ref(), &referenced))??;
  let expander = build_expander(env.clone());
  let home = expand_value(&expander, &raw_home)?;
  let host_home = home_dir();
  let includes: Vec<PathBuf> = config
    .workspace
    .include
    .iter()
    .map(|entry| expand_path(&expander, &entry.to_string_lossy()).map(PathBuf::from))
    .collect::<Result<_, Error>>()?;
  let entries = include_entries(root, &includes, host_home.as_deref())?;
  let mounts = covering(
    entries
      .into_iter()
      .map(|(host, ro)| Mount {
        container: translate(&host, host_home.as_deref(), &home),
        host,
        ro,
      })
      .collect(),
  );
  let decoys = with_rule_patterns(select(fnox.as_ref(), &registry), &registry, &config.rules);
  validate_passthrough(&config.rules, &decoys, &config.workspace.passthrough)?;
  let kube_ca = rewrite_ca(&config.workspace.file_rewrite)?;
  let guests_dir = workspace_state_dir(root).join("guests");
  let rewritten = write_rewrites(&RewriteInputs {
    files_dir: &workspace_state_dir(root).join("files"),
    root,
    rewrites: &config.workspace.file_rewrite,
    decoys: &decoys,
    env: &env,
    expander: &expander,
    home: &home,
    host_home: host_home.as_deref(),
    kube_ca: kube_ca.as_ref(),
    guests_dir: &guests_dir,
  })?;
  let grants_state = workspace_state_dir(root).join("grants");
  adapt::write_state(&grants_state, &rewritten.grants)?;
  let grants_mounts = if rewritten.grants.is_empty() {
    Vec::new()
  } else {
    vec![Mount {
      host: grants_state,
      container: PathBuf::from(GRANTS_STATE_DIR),
      ro: true,
    }]
  };
  let global_profiles = hodor_config::config::config_dir().map(|dir| dir.join("profiles"));
  let project_profiles = hodor_config::config::project_profiles_dir(root);
  let roots = ProfileRoots {
    project: Some(project_profiles.as_path()),
    global: global_profiles.as_deref(),
  };
  let tool_mounts = profile_mounts(&roots, config.workspace.profile_name(), &config.tools, &home)?;
  let guest = guest_mounts(&config, &guests_dir, &home)?;
  let fnox = fnox_binds(fnox_config_dir(host_home.as_deref()).as_deref(), config_dir().as_deref());
  let root_container = translate(root, host_home.as_deref(), &home);
  let project = config.workspace.name.clone().unwrap_or_else(|| workspace_slug(root));
  let storage = workspace_state_dir(root).join("containers");
  let uid = current_uid();
  Ok(
    Stack {
      backend,
      project,
      decoys,
      agent: AgentSpec {
        root: &root_container,
        home: &home,
        storage: &storage,
        uid,
      },
      mounts,
      tool_mounts,
      fnox,
      guest,
      init: config.workspace.init.clone(),
      ports: config.workspace.ports.clone(),
      passthrough: config.workspace.passthrough.clone(),
      file_mounts: rewritten.mounts,
      grants_mounts,
      hodor_version,
    }
    .render(),
  )
}

/// The guest-identity CA when the workspace declares file rewrites: their
/// adapters mint guest pairs from it.
fn rewrite_ca(rewrites: &[FileRewrite]) -> Result<Option<CertAuthority>, Error> {
  if rewrites.is_empty() {
    return Ok(None);
  }
  let ca_path = config_dir()
    .ok_or_else(|| Error::ConfigDir {
      detail: "file rewrites need the hodor config directory to load the CA from".to_string(),
    })?
    .join("ca.pem");
  load_or_generate(&ca_path).map(Some).map_err(|source| Error::GuestCa {
    path: ca_path.clone(),
    source,
  })
}

/// Mounts for minted guest identities when any rule requests mTLS, else none.
fn guest_mounts(config: &AppConfig, guests_dir: &Path, home: &str) -> Result<Vec<Mount>, Error> {
  if !config
    .rules
    .values()
    .any(|rule| rule.tls.values().any(|tls| tls.guest_tls_mode == GuestTlsMode::Mtls))
  {
    return Ok(Vec::new());
  }
  let ca_path = config_dir()
    .ok_or_else(|| Error::ConfigDir {
      detail: "a guest identity needs the hodor config directory to load the CA from".to_string(),
    })?
    .join("ca.pem");
  let ca = load_or_generate(&ca_path).map_err(|source| Error::GuestCa {
    path: ca_path.clone(),
    source,
  })?;
  guest_identity_mounts(&config.rules, &ca, guests_dir, home)
}

/// Real/decoy byte pairs for one rewrite's env names, in declared order.
pub(crate) type RewritePairs = Vec<(Vec<u8>, Vec<u8>)>;

/// Real/decoy byte pairs for one rewrite's env names, in declared order.
///
/// # Errors
///
/// Returns an error naming the env when a name has no known real value or
/// no decoy.
fn rewrite_pairs(rewrite: &FileRewrite, env: &HashMap<String, String>, by_env: &BTreeMap<&str, &str>) -> Result<RewritePairs, Error> {
  let mut pairs = Vec::new();
  for name in &rewrite.envs {
    let real = env
      .get(name)
      .filter(|value| !value.is_empty())
      .ok_or_else(|| Error::RewriteNoValue {
        file: rewrite.source.clone(),
        name: name.clone(),
      })?;
    let decoy = by_env.get(name.as_str()).ok_or_else(|| Error::RewriteNoDecoy {
      file: rewrite.source.clone(),
      name: name.clone(),
    })?;
    pairs.push((real.as_bytes().to_vec(), decoy.as_bytes().to_vec()));
  }
  Ok(pairs)
}

/// Inputs for [`write_rewrites`]: the generation context the rewrite loop
/// reads, as one value instead of eight positional arguments.
pub(crate) struct RewriteInputs<'a> {
  /// State directory the rewritten files land in.
  pub(crate) files_dir: &'a Path,
  /// Workspace root relative sources resolve against.
  pub(crate) root: &'a Path,
  /// Rewrite entries from `[workspace] file_rewrite`.
  pub(crate) rewrites: &'a [FileRewrite],
  /// Selected decoys supplying the replacement values.
  pub(crate) decoys: &'a [Decoy],
  /// Resolved real values keyed by env name.
  pub(crate) env: &'a HashMap<String, String>,
  /// Xpanda expander for sources and dests.
  pub(crate) expander: &'a Xpanda,
  /// Container home expanding `{home}` in dests.
  pub(crate) home: &'a str,
  /// Host home relative sources and `~` expand against.
  pub(crate) host_home: Option<&'a Path>,
  /// Guest-identity CA, preloaded by generation or injected by tests; the
  /// kube adapter mints the guest pair from it.
  pub(crate) kube_ca: Option<&'a CertAuthority>,
  /// Guest pairs mint here; the kube adapter reads them back for the decoy.
  pub(crate) guests_dir: &'a Path,
}

/// What `write_rewrites` produces: the agent mounts plus the tool-config
/// grants whose fragments land in the state grant layer.
#[derive(Debug)]
pub(crate) struct RewriteOutputs {
  /// Read-only mounts of the rewritten files at their dests.
  pub(crate) mounts: Vec<Mount>,
  /// Grants adapted from kubeconfig and talosconfig sources.
  pub(crate) grants: Vec<RewriteAdapted>,
}

/// Rewrite each `file_rewrite` source with decoys and write the outputs under
/// `files_dir`, returning a read-only mount per entry at its `{home}`-expanded
/// dest. Kubeconfig sources take the adapter path instead: the file is the
/// secret source, so they state no `envs`, and the grant layer writes from
/// the returned grants.
///
/// # Errors
///
/// Returns an error naming the variable when a path fails to expand, naming
/// the env name when a rewrite names one with no known real value or no
/// decoy, when a kubeconfig source states `envs` or does not map, or when a
/// source file cannot be read or an output written.
pub(crate) fn write_rewrites(inputs: &RewriteInputs<'_>) -> Result<RewriteOutputs, Error> {
  let RewriteInputs {
    files_dir,
    root,
    rewrites,
    decoys,
    env,
    expander,
    home,
    host_home,
    kube_ca: preloaded_ca,
    guests_dir,
  } = *inputs;
  if rewrites.is_empty() {
    return Ok(RewriteOutputs {
      mounts: Vec::new(),
      grants: Vec::new(),
    });
  }
  let by_env: BTreeMap<&str, &str> = decoys.iter().map(|decoy| (decoy.env.as_str(), decoy.value.as_str())).collect();
  fs::create_dir_all(files_dir).map_err(|source| Error::CreateDir {
    path: files_dir.to_path_buf(),
    source,
  })?;
  let mut mounts = Vec::new();
  let mut grants = Vec::new();
  let mut owned_ca: Option<CertAuthority> = None;
  for (index, rewrite) in rewrites.iter().enumerate() {
    let pairs = rewrite_pairs(rewrite, env, &by_env)?;
    let expanded_source = PathBuf::from(expand_path(expander, &rewrite.source.to_string_lossy())?);
    let host = expand(&expanded_source, root, host_home);
    let content = fs::read(&host).map_err(|source| Error::ReadFile {
      path: host.clone(),
      source,
    })?;
    let format = rewrite.format.or_else(|| sniff(&content));
    let out_bytes = match format {
      Some(format) => {
        if !rewrite.envs.is_empty() {
          return Err(Error::RewriteWithEnvs {
            file: rewrite.source.clone(),
            format,
          });
        }
        let ca: &CertAuthority = if let Some(ca) = preloaded_ca {
          ca
        } else {
          let ca_path = config_dir()
            .ok_or_else(|| Error::ConfigDir {
              detail: "an adapted rewrite needs the hodor config directory to load the CA from".to_string(),
            })?
            .join("ca.pem");
          owned_ca.insert(load_or_generate(&ca_path).map_err(|source| Error::GuestCa {
            path: ca_path.clone(),
            source,
          })?)
        };
        let adapted: Vec<RewriteAdapted> = match format {
          RewriteFormat::Kubeconfig => kube::adapt(&host, &content, ca, guests_dir)?.into_iter().collect(),
          RewriteFormat::Talos => Vec::from([talos::adapt(&host, &content, ca, guests_dir)?]),
          RewriteFormat::Ssh => {
            let host_home = host_home.ok_or_else(|| Error::ConfigDir {
              detail: "an ssh rewrite needs the host home to resolve identities".to_string(),
            })?;
            ssh::adapt(&host, &content, home, host_home)?
          }
        };
        match adapted.first() {
          Some(first) => {
            let bytes = first.decoy.clone().into_bytes();
            for file in &first.decoy_files {
              let file_path = files_dir.join(&file.name);
              fs::write(&file_path, &file.bytes).map_err(|source| Error::WriteFile {
                path: file_path.clone(),
                source,
              })?;
              mounts.push(Mount {
                host: file_path,
                container: PathBuf::from(&file.container),
                ro: true,
              });
            }
            grants.extend(adapted);
            bytes
          }
          None if rewrite.format.is_some() => {
            return Err(Error::RewriteInvalid {
              file: host.clone(),
              format,
              detail: "the document does not carry the format's markers".to_string(),
            });
          }
          None => apply_rewrites(&content, &pairs),
        }
      }
      None => apply_rewrites(&content, &pairs),
    };
    let out_path = files_dir.join(rewrite_file_name(index, &host));
    fs::write(&out_path, out_bytes).map_err(|source| Error::WriteFile {
      path: out_path.clone(),
      source,
    })?;
    let container = expand_value(expander, &rewrite.dest)?.replace("{home}", home);
    if !container.starts_with('/') {
      return Err(Error::RewriteDestNotAbsolute {
        dest: rewrite.dest.clone(),
      });
    }
    mounts.push(Mount {
      host: out_path,
      container: PathBuf::from(container),
      ro: true,
    });
  }
  Ok(RewriteOutputs { mounts, grants })
}

/// The process's user id, from the kernel: the same value `id -u` prints,
/// without the subprocess.
pub(crate) fn current_uid() -> u32 {
  // Safety: `getuid` takes no arguments, cannot fail, and touches no memory.
  unsafe { getuid() }
}

/// `hodor rules` TOML for the selection: what derivation substitutes, what
/// still needs a host, and what no registry entry covers.
pub(crate) fn rules_toml(decoys: &[Decoy], hostless: &[Decoy], unregistered: &[String]) -> String {
  let mut out = String::from(
    "# `hodor rules` — what this workspace's proxy substitutes.\n\
     #\n\
     # The catalog derives at serve time: every fnox-declared name the registry\n\
     # gives hosts becomes a rule, its value resolving from fnox. Config states\n\
     # overrides only — a [rules.<env>] block in the workspace\n\
     # `.config/hodor/config.toml` or the global `<config-dir>/hodor/config.toml`,\n\
     # where the workspace file wins per label; its `allow` unions with the\n\
     # registry hosts, and `registry = false` keeps only `allow`. To give a name\n\
     # hosts in every workspace instead, add an override file in\n\
     # `<config-dir>/hodor/rules.d/` or `<workspace root>/.config/hodor/rules.d/`.\n",
  );
  if !decoys.is_empty() {
    out.push_str("#\n# derives automatically, hosts from the registry:\n");
    for decoy in decoys {
      let _ = writeln!(out, "#   {}", decoy.env);
    }
  }
  if !hostless.is_empty() {
    out.push_str(
      "#\n\
       # The registry knows these names but states no hosts: either the endpoint is\n\
       # per deployment (self-hosted control planes) or the value is a signing input\n\
       # that never reaches the wire (exchange API secrets — see\n\
       # https://github.com/casualjim/hodor/issues/19). Name the endpoint to use the\n\
       # key as a rule, or drop it from fnox to stop emitting a decoy:\n\
       #\n",
    );
    for decoy in hostless {
      let _ = writeln!(
        out,
        "# [rules.{}]\n# env = \"{}\"\n# allow = [\"https://<your-host>\"]\n",
        decoy.env.to_lowercase(),
        decoy.env
      );
    }
  }
  if !unregistered.is_empty() {
    let _ = writeln!(
      out,
      "#\n# fnox declares these but no registry entry covers them, so nothing derives:\n# {}\n",
      unregistered.join(", ")
    );
  }
  out
}

/// What the generated agent service is built from: container-side paths and
/// the host directory mounted as the inner runtime's storage.
pub(crate) struct AgentSpec<'a> {
  /// Workspace root, translated into the agent container.
  pub(crate) root: &'a Path,
  /// The agent user's home directory in the container.
  pub(crate) home: &'a str,
  /// Host directory mounted at `{home}/.local/share/containers`.
  pub(crate) storage: &'a Path,
  /// Host uid baked as the agent user: mounts the agent writes must be its own.
  pub(crate) uid: u32,
}

/// What the hodor service runs for a capture backend, the extra capabilities
/// that needs, and the service keys that go with it.
fn backend_service(backend: ProxyBackend, project: &str) -> (String, &'static [&'static str], String) {
  match backend {
    ProxyBackend::Ebpf => (
      "[\"serve\", \"--proxy-backend\", \"ebpf\", \"--ebpf-cgroup\", \"enclosing\"]".to_string(),
      &["BPF", "PERFMON"],
      // Both services carry the same `cgroup_parent`, so docker creates that
      // cgroup as part of hodor's own start and hodor attaches to it by
      // resolving its parent from `/proc/self/cgroup`: the daemon resolves the
      // parent relative to its own cgroup root, which is why no host path is
      // written down here.
      format!("    cgroup: host\n    cgroup_parent: hodor-{project}.slice\n"),
    ),
    ProxyBackend::Tun => (
      "[\"serve\", \"--proxy-backend\", \"tun\"]".to_string(),
      &[],
      "    devices: [/dev/net/tun]\n".to_string(),
    ),
    ProxyBackend::Tproxy => ("[\"serve\", \"--proxy-backend\", \"tproxy\"]".to_string(), &[], String::new()),
    // `hodor init` rejects `none`; rendered anyway so this match is exhaustive.
    ProxyBackend::None => ("[\"serve\"]".to_string(), &[], String::new()),
  }
}

/// A stack to generate: every input compose rendering reads, as one value.
/// [`generate_stack`] fills it from a workspace; tests build it literally.
pub(crate) struct Stack<'a> {
  pub(crate) backend: ProxyBackend,
  pub(crate) project: String,
  pub(crate) decoys: Vec<Decoy>,
  pub(crate) agent: AgentSpec<'a>,
  pub(crate) mounts: Vec<Mount>,
  pub(crate) tool_mounts: Vec<Mount>,
  pub(crate) fnox: FnoxBinds,
  pub(crate) guest: Vec<Mount>,
  pub(crate) init: Option<String>,
  /// Ports the hodor service publishes as stable host `127.0.0.1` bindings,
  /// from `[workspace] ports`.
  pub(crate) ports: Vec<u16>,
  /// Env names forwarded as `${NAME}` interpolation in the agent
  /// environment, from `[workspace] passthrough`.
  pub(crate) passthrough: Vec<String>,
  /// Rewritten files mounted read-only at their dests, from
  /// `[workspace] file_rewrite`; after workspace mounts so they win.
  pub(crate) file_mounts: Vec<Mount>,
  /// Upstream identity files adapter grants materialize: mounted into the
  /// hodor service at their absolute paths, so host and container serve
  /// resolve the same fragment entries. Never into the agent: real secrets
  /// stay out.
  pub(crate) grants_mounts: Vec<Mount>,
  /// Hodor image tag: the binary's version, threaded from the binary crate.
  /// Library crates version independently, so `env!` here would lie.
  pub(crate) hodor_version: &'a str,
}

impl Stack<'_> {
  /// The compose file this stack renders to.
  pub(crate) fn render(&self) -> String {
    let (serve, extra_caps, service_extra) = backend_service(self.backend, &self.project);
    let mut out = String::new();
    let grants_env = if self.grants_mounts.is_empty() {
      String::new()
    } else {
      format!("      HODOR_CONFIG: {GRANTS_STATE_DIR}/hodor.toml\n")
    };
    let _ = write!(
      out,
      "# stack shape: {shape}\n\
       # generated by `hodor init` — edit freely; the file regenerates when the\n\
       # workspace config or the shape above changed since it was generated.\n\
       # hodor merges config like always\n\
       # (global layer plus this workspace's .config/hodor/config.toml, discovered
       # from its working directory, plus the generated tool-config grant layer
       # when a rewrite adapts one); the agent holds decoys only.\n\
       name: {project}\n\
       services:\n\
       \x20 hodor:\n\
       \x20   image: ghcr.io/casualjim/hodor:{version}\n\
       \x20   working_dir: \"{root}\"\n\
       \x20   command: {serve}\n\
       {service_extra}\
       \x20   environment:\n\
       \x20     RUST_LOG: info\n\
       \x20     HODOR_CA_FILE: /certs/ca.pem\n\
       \x20     # 8080 must stay free on loopback: agent dev servers default\n\
       \x20     # to it, and the explicit proxy's default bind would squat on\n\
       \x20     # 127.0.0.1:8080, leaving the fwd sidecar nothing to expose.\n\
       \x20     HODOR_LISTEN: {listen}\n{grants_env}",
      root = self.agent.root.display(),
      project = self.project,
      listen = EXPLICIT_LISTEN,
      version = self.hodor_version,
      shape = STACK_SHAPE
    );
    out.push_str(
      "    cap_add:\n\
       \x20     - NET_ADMIN\n",
    );
    for cap in extra_caps {
      let _ = writeln!(out, "      - {cap}");
    }
    if !self.ports.is_empty() {
      out.push_str("    ports:\n");
      for port in &self.ports {
        // Same port both sides: the fwd sidecar holds the netns's own bridge
        // address for each exposed agent listener, and a stable host binding
        // names it instead of the changing bridge IP. Fixed at create:
        // applying a change takes a restart.
        let _ = writeln!(out, "      - \"127.0.0.1:{port}:{port}\"");
      }
    }
    out.push_str(
      "    stop_grace_period: 1s\n\
       \x20   volumes:\n",
    );
    for mount in &self.mounts {
      let mode = if mount.ro { "ro" } else { "rw" };
      let _ = writeln!(out, "      - {}:{}:{mode}", mount.host.display(), mount.container.display());
    }
    let _ = writeln!(
      out,
      "      - {}:/certs/ca.pem",
      config_dir()
        .unwrap_or_else(|| Path::new("~/.config/hodor").to_path_buf())
        .join("ca.pem")
        .display()
    );
    for mount in &self.fnox.mounts {
      let _ = writeln!(out, "      - {}:{}:ro", mount.host.display(), mount.container.display());
    }
    for mount in &self.grants_mounts {
      let _ = writeln!(out, "      - {}:{}:ro", mount.host.display(), mount.container.display());
    }
    out.push_str(&self.agent_service());
    out.push_str(&self.fwd_service());
    out
  }

  /// The agent service: it shares hodor's network namespace and holds decoys
  /// only, plus the backend's cgroup placement when the capture needs one. The
  /// hooks only capture processes inside the cgroup they attach to, so this
  /// service lands in it and hodor stays outside.
  fn agent_service(&self) -> String {
    let cgroup = match self.backend {
      ProxyBackend::Ebpf => format!(
        "    # Both services sit in this cgroup and hodor attaches to it: the hooks\n\
       \x20   # capture what is inside, and hodor's own sockets are skipped by\n\
       \x20   # the recorded proxy PID.\n\
       \x20   cgroup_parent: hodor-{}.slice\n",
        self.project
      ),
      ProxyBackend::Tun | ProxyBackend::Tproxy | ProxyBackend::None => String::new(),
    };
    let mut out = String::new();
    let _ = write!(
      out,
      "\n\
     \x20 agent:\n\
     \x20   image: ghcr.io/casualjim/devagent:26.04\n\
     \x20   # The agent runs containers of its own, which is what the widened\n\
     \x20   # privileges are for: inner containers mount, chroot and raise their\n\
     \x20   # own networking, so seccomp/systempaths/apparmor are unconfined and\n\
     \x20   # SYS_ADMIN is granted. apparmor=unconfined is what Ubuntu's default\n\
     \x20   # profile requires and is inert where AppArmor is not loaded.\n\
     \x20   # systempaths=unconfined is podman-only: drop it under docker.\n\
     \x20   security_opt: [seccomp=unconfined, systempaths=unconfined, apparmor=unconfined]\n\
     \x20   cap_add: [SYS_CHROOT, AUDIT_WRITE, NET_ADMIN, SETUID, SETGID, SYS_ADMIN]\n\
     \x20   devices: [/dev/net/tun]\n\
     {cgroup}\
     \x20   # docker-init (tini) as pid 1: signal handling and child reaping\n\
     \x20   # for the long-running shells this container hosts\n\
     \x20   init: true\n\
     \x20   user: \"{uid}\"\n\
     \x20   working_dir: \"{root}\"\n\
     \x20   entrypoint: [\"{home}/.config/hodor/agent-entrypoint.sh\"]\n\
     \x20   command: [\"sleep\", \"infinity\"]\n\
     \x20   environment:\n\
     \x20     # The entrypoint installs the CA into the system store. Node and\n\
     \x20     # Python's requests read their own bundle, so point them at it.\n\
     \x20     NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt\n\
     \x20     REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt\n\
     \x20     # decoys — one per declared rule, swapped by hodor on grant match\n",
      root = self.agent.root.display(),
      home = self.agent.home,
      uid = self.agent.uid
    );
    if let Some(init) = &self.init {
      let _ = writeln!(out, "      HODOR_INIT: \"{init}\"");
    }
    for decoy in &self.decoys {
      let _ = writeln!(out, "      {}: \"{}\"", decoy.env, decoy.value);
    }
    if !self.passthrough.is_empty() {
      out.push_str("      # passthrough — compose interpolates these from the host at `up`, never baked\n");
    }
    for name in &self.passthrough {
      // Single `$`: compose substitutes the host value when the stack starts,
      // so the file holds no secret and values stay fresh without regenerating.
      let _ = writeln!(out, "      {name}: \"${{{name}}}\"");
    }
    out.push_str("    volumes:\n");
    for mount in self
      .mounts
      .iter()
      .chain(&self.file_mounts)
      .chain(&self.tool_mounts)
      .chain(&self.guest)
    {
      let mode = if mount.ro { "ro" } else { "rw" };
      let _ = writeln!(out, "      - {}:{}:{mode}", mount.host.display(), mount.container.display());
    }
    let cfg_dir = config_dir();
    let entrypoint_host = cfg_dir
      .as_deref()
      .unwrap_or_else(|| Path::new("~/.config/hodor"))
      .join("agent-entrypoint.sh");
    let ca_crt_host = cfg_dir.as_deref().unwrap_or_else(|| Path::new("~/.config/hodor")).join("ca.crt");
    let _ = write!(
      out,
      "      - {}:{home}/.config/hodor/agent-entrypoint.sh:ro\n\
     \x20     - {}:/usr/local/share/ca-certificates/hodor-ca.crt:ro\n\
     \x20     # Inner container storage. Made at generation time under this\n\
     \x20     # workspace's state directory, owned by the user that runs the\n\
     \x20     # agent: a bind source the runtime creates itself is root-owned,\n\
     \x20     # and podman inside then dies without a word. A named volume needs\n\
     \x20     # the same ownership once, by hand.\n\
     \x20     - {storage}:{home}/.local/share/containers\n\
     \x20   network_mode: \"service:hodor\"\n",
      entrypoint_host.display(),
      ca_crt_host.display(),
      home = self.agent.home,
      storage = self.agent.storage.display()
    );
    out
  }

  /// The exposure sidecar: hodor's netns to see every listener of the shared
  /// namespace, the agent's PID namespace so only agent-owned processes can
  /// ever be attributed a listener — hodor's capture and explicit-proxy
  /// listeners and docker's embedded DNS are structurally unattributable
  /// from here and are never forwarded. The hodor image runs it because the
  /// sidecar needs no image of its own and no payload inspection: `hodor
  /// fwd` relays raw bytes.
  fn fwd_service(&self) -> String {
    let mut out = String::new();
    let _ = write!(
      out,
      "\n\
     \x20 fwd:\n\
     \x20   image: ghcr.io/casualjim/hodor:{version}\n\
     \x20   command: [\"fwd\"]\n\
     \x20   # Shares the netns and the agent's PID namespace; publishing is on\n\
     \x20   # the hodor service, and anything else it could reach is bound to\n\
     \x20   # the netns itself. Never a PID namespace shared with hodor: the\n\
     \x20   # agent holds the decoys, hodor the real secrets.\n\
     \x20   network_mode: \"service:hodor\"\n\
     \x20   pid: \"service:agent\"\n",
      version = self.hodor_version
    );
    out
  }
}

/// Container location each tool reads its config from by default, keyed by the
/// directory name under `profiles/<profile>/`. `{home}` expands to
/// `[workspace] home`. `[tools.<name>] config_dir` overrides an entry or adds
/// one the table does not carry.
pub(crate) const TOOL_CONFIG_DIRS: &[(&str, &str)] = &[
  ("amazon-q", "{home}/.aws/amazonq"),
  ("amazonq", "{home}/.aws/amazonq"),
  ("amp", "{home}/.config/amp"),
  ("auggie", "{home}/.augment"),
  ("augment", "{home}/.augment"),
  ("claude", "{home}/.claude"),
  ("claude-code", "{home}/.claude"),
  ("cline", "{home}/.cline"),
  ("codebuddy", "{home}/.codebuddy"),
  ("codebuff", "{home}/.config/manicode"),
  ("codex", "{home}/.codex"),
  ("codex-cli", "{home}/.codex"),
  ("continue", "{home}/.continue"),
  ("copilot", "{home}/.copilot"),
  ("crush", "{home}/.config/crush"),
  ("cursor", "{home}/.cursor"),
  ("deepagents", "{home}/.deepagents"),
  ("droid", "{home}/.factory"),
  ("dsh", "{home}/.dsh"),
  ("factory", "{home}/.factory"),
  ("forge", "{home}/.forge"),
  ("gemini", "{home}/.gemini"),
  ("gemini-cli", "{home}/.gemini"),
  ("gh", "{home}/.config/gh"),
  ("goose", "{home}/.config/goose"),
  ("gptme", "{home}/.config/gptme"),
  ("grok", "{home}/.grok"),
  ("grok-build", "{home}/.grok"),
  ("hermes", "{home}/.hermes"),
  ("iflow", "{home}/.iflow"),
  ("junie", "{home}/.junie"),
  ("junie-cli", "{home}/.junie"),
  ("kilo", "{home}/.config/kilo"),
  ("kimi", "{home}/.kimi"),
  ("kimi-code", "{home}/.kimi-code"),
  ("kiro", "{home}/.kiro"),
  ("kiro-cli", "{home}/.kiro"),
  ("mimo", "{home}/.mimo-code"),
  ("mimo-code", "{home}/.mimo-code"),
  ("muse", "{home}/.muse-code"),
  ("muse-code", "{home}/.muse-code"),
  ("omp", "{home}/.omp"),
  ("open-interpreter", "{home}/.config/open-interpreter"),
  ("openclaw", "{home}/.openclaw"),
  ("openhands", "{home}/.openhands"),
  ("openinterpreter", "{home}/.config/open-interpreter"),
  ("opencode", "{home}/.config/opencode"),
  ("pi", "{home}/.pi"),
  ("qoder", "{home}/.qoder"),
  ("qwen", "{home}/.qwen"),
  ("qwen-code", "{home}/.qwen"),
  ("roo", "{home}/.config/roo"),
  ("roo-code", "{home}/.config/roo"),
  ("trae", "{home}/.trae"),
  ("vibe", "{home}/.vibe"),
  ("warp", "{home}/.config/warp-terminal"),
  ("workbuddy", "{home}/.codebuddy"),
];

/// Profile roots searched for tool configs: the workspace's own directory
/// first, the global one next.
pub(crate) struct ProfileRoots<'a> {
  /// `<root>/.config/hodor/profiles/`, when generation knows the workspace.
  pub(crate) project: Option<&'a Path>,
  /// `<config-dir>/hodor/profiles/`, when the global config resolves.
  pub(crate) global: Option<&'a Path>,
}

/// Mount the selected profile's tool configs at the locations the tools read
/// by default, so nothing has to point a tool at them. Each tool resolves
/// down its inheritance chain in the project layer first, then the global
/// one. Writable: the tool owns that directory, and its writes
/// land beside the profile on the host. The shared base root is always
/// created; a tool named in `[tools]` but found nowhere is created under the
/// selected profile in the workspace layer, or the global one when
/// generation has no workspace root.
pub(crate) fn profile_mounts(
  roots: &ProfileRoots,
  profile: &str,
  configured: &BTreeMap<String, ToolCfg>,
  home: &str,
) -> Result<Vec<Mount>, Error> {
  let chain = hodor_config::config::profile_chain(roots.project, roots.global, profile)?;
  if let Some(global) = roots.global {
    let dir = global.join(SHARED_PROFILE);
    fs::create_dir_all(&dir).map_err(|source| Error::CreateDir { path: dir.clone(), source })?;
  }
  let mut names: Vec<String> = TOOL_CONFIG_DIRS.iter().map(|(tool, _)| (*tool).to_string()).collect();
  names.extend(configured.keys().cloned());
  names.sort();
  names.dedup();
  let mut mounts = Vec::new();
  for name in &names {
    if !valid_profile(name) {
      return Err(Error::ToolNameInvalid { name: name.clone() });
    }
    let template = configured
      .get(name)
      .map(|tool| tool.config_dir.as_str())
      .or_else(|| TOOL_CONFIG_DIRS.iter().find(|(tool, _)| tool == name).map(|(_, dir)| *dir));
    let Some(template) = template else {
      continue;
    };
    let container = template.replace("{home}", home);
    if !container.starts_with('/') {
      return Err(Error::ToolConfigNotAbsolute {
        name: name.clone(),
        template: template.to_string(),
      });
    }
    let mut host = None;
    for layer in [roots.project, roots.global].into_iter().flatten() {
      if let Some(dir) = chain.iter().map(|parent| layer.join(parent).join(name)).find(|dir| dir.is_dir()) {
        host = Some(dir);
        break;
      }
    }
    if host.is_none()
      && configured.contains_key(name)
      && let Some(base) = roots.project.or(roots.global)
    {
      let dir = base.join(profile).join(name);
      fs::create_dir_all(&dir).map_err(|source| Error::CreateDir { path: dir.clone(), source })?;
      host = Some(dir);
    }
    if let Some(host) = host {
      mounts.push(Mount {
        host,
        container: PathBuf::from(container),
        ro: false,
      });
    }
  }
  Ok(mounts)
}

/// Registry for the generation commands: bundled table, global `rules.d`,
/// then the workspace's own.
pub(crate) fn generation_registry(root: Option<&Path>) -> Result<Registry, Error> {
  Ok(Registry::load_union(
    rules_dir().as_deref(),
    root.map(project_rules_dir).as_deref(),
  )?)
}

/// Open fnox via its own discovery; no hodor-specific env vars.
pub(crate) fn open_fnox() -> Result<Option<FnoxSource>, Error> {
  Ok(FnoxSource::open()?)
}

/// The workspace's state directory: `<state-dir>/hodor/ws/<slug>`. The
/// generated stack lives here and the agent's inner-runtime storage sits
/// beside it.
pub(crate) fn workspace_state_dir(root: &Path) -> PathBuf {
  state_dir()
    .unwrap_or_else(|| PathBuf::from("."))
    .join("hodor")
    .join("ws")
    .join(workspace_slug(root))
}

/// The workspace's override file: `hodor.compose.yaml` first, then `.yml`.
pub(crate) fn workspace_file(root: &Path) -> PathBuf {
  let yaml = root.join(".config").join("hodor.compose.yaml");
  if yaml.is_file() {
    return yaml;
  }
  root.join(".config").join("hodor.compose.yml")
}

/// Stable directory slug for a workspace root: lowercase path segments
/// joined with dashes.
pub(crate) fn workspace_slug(root: &Path) -> String {
  let slug: Vec<String> = root
    .components()
    .filter_map(|component| match component {
      Component::Normal(part) => {
        let text = part.to_string_lossy().to_lowercase();
        let cleaned: String = text.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '-' }).collect();
        (!cleaned.trim_matches('-').is_empty()).then(|| cleaned.trim_matches('-').to_string())
      }
      _ => None,
    })
    .collect();
  slug.join("-")
}

/// The workspace's own config, as generation and support-file setup read it:
/// the unified project layer when it exists, the legacy flat file otherwise,
/// and the unified path itself when neither does — a workspace with no config
/// has no project layer at all, never one discovered from the process cwd.
pub(crate) fn workspace_config(root: &Path) -> Result<AppConfig, Error> {
  let cli = Cli {
    config: Some(project_config_file(root).unwrap_or_else(|| project_config_write_path(root))),
  };
  Ok(load(&cli, None)?.0)
}

#[cfg(test)]
mod tests {
  use super::{guest_identity_mounts, uncovered_names, uncovered_warning, validate_passthrough};
  use hodor_config::config::{HostTlsCfg, IfMissing, RuleCfg};
  use hodor_config::grants::GuestTlsMode;
  use hodor_pki::ca::CertAuthority;
  use std::collections::{BTreeMap, BTreeSet};
  use std::fs;
  use std::path::PathBuf;

  fn mtls_rule(guest_cert: Option<&str>, guest_key: Option<&str>) -> BTreeMap<String, RuleCfg> {
    let mut tls = BTreeMap::new();
    tls.insert(
      "https://api.github.com".to_string(),
      HostTlsCfg {
        client_cert: None,
        client_key: None,
        root_cert: None,
        guest_tls_mode: GuestTlsMode::Mtls,
        guest_cert: guest_cert.map(PathBuf::from),
        guest_key: guest_key.map(PathBuf::from),
      },
    );
    let rule = RuleCfg {
      env: "GITHUB_TOKEN".into(),
      value: None,
      real: None,
      fnox_key: None,
      allow: vec!["https://api.github.com".to_string()],
      pattern: None,
      registry: None,
      oauth2: None,
      tls,
      ssh: BTreeMap::new(),
      if_missing: IfMissing::default(),
    };
    let mut rules = BTreeMap::new();
    rules.insert("github".to_string(), rule);
    rules
  }

  /// One minted pair per rule, mounted read-only at the declared container
  /// paths, and the second call is a no-op: the pair on disk is kept.
  #[test]
  fn guest_identity_mounts_declared_paths_and_keeps_an_existing_pair() {
    let ca = CertAuthority::generate().unwrap();
    let dir = tempfile::tempdir().unwrap();
    let guests = dir.path().join("guests");
    let rules = mtls_rule(Some("/safe/cert.pem"), Some("/safe/cert.key"));
    let mounts = guest_identity_mounts(&rules, &ca, &guests, "/root").unwrap();
    assert_eq!(mounts.len(), 2);
    assert_eq!(mounts[0].container, PathBuf::from("/safe/cert.pem"));
    assert_eq!(mounts[1].container, PathBuf::from("/safe/cert.key"));
    assert!(mounts.iter().all(|mount| mount.ro));
    assert!(mounts[0].host.is_file() && mounts[1].host.is_file());
    let cert_before = fs::read(&mounts[0].host).unwrap();
    let again = guest_identity_mounts(&rules, &ca, &guests, "/root").unwrap();
    assert_eq!(again[0].host, mounts[0].host);
    assert_eq!(fs::read(&mounts[0].host).unwrap(), cert_before);
  }

  /// An entry that declares no container paths gets the per-rule default
  /// under the agent's home.
  #[test]
  fn guest_identity_defaults_the_container_paths_when_none_declared() {
    let ca = CertAuthority::generate().unwrap();
    let dir = tempfile::tempdir().unwrap();
    let rules = mtls_rule(None, None);
    let mounts = guest_identity_mounts(&rules, &ca, &dir.path().join("guests"), "/root").unwrap();
    assert_eq!(mounts[0].container, PathBuf::from("/root/.config/hodor/guest/github.pem"));
    assert_eq!(mounts[1].container, PathBuf::from("/root/.config/hodor/guest/github.key"));
  }

  /// A passthrough name that is also a rule env or a decoy fails, naming
  /// the name; disjoint names pass.
  #[test]
  fn passthrough_overlapping_a_rule_or_decoy_fails() {
    let rules = mtls_rule(None, None);
    let decoys = vec![super::Decoy {
      env: "ANTHROPIC_API_KEY".to_string(),
      value: "decoy".to_string(),
    }];
    let error = validate_passthrough(&rules, &[], &["GITHUB_TOKEN".to_string()])
      .unwrap_err()
      .to_string();
    assert!(error.contains("GITHUB_TOKEN"), "{error}");
    let error = validate_passthrough(&rules, &decoys, &["ANTHROPIC_API_KEY".to_string()])
      .unwrap_err()
      .to_string();
    assert!(error.contains("ANTHROPIC_API_KEY"), "{error}");
    validate_passthrough(&rules, &decoys, &["DISPLAY".to_string()]).unwrap();
  }

  /// Uncovered keeps declared names minus selection, passthrough, and
  /// fnox's own wiring; the warning sorts and names them with a fix.
  #[test]
  fn uncovered_diff_excludes_selected_passthrough_and_fnox_wiring() {
    let declared = BTreeSet::from([
      "GITHUB_TOKEN".to_string(),
      "WAYLAND_DISPLAY".to_string(),
      "DISPLAY".to_string(),
      "FNOX_PROFILE".to_string(),
    ]);
    let uncovered = uncovered_names(&declared, &["GITHUB_TOKEN".to_string()], &["WAYLAND_DISPLAY".to_string()]);
    assert_eq!(uncovered, vec!["DISPLAY".to_string()]);
    let warning = uncovered_warning(&["B".to_string(), "A".to_string()]).unwrap();
    assert!(warning.contains("A, B"), "{warning}");
    assert!(warning.contains("[workspace] passthrough"), "{warning}");
    assert_eq!(uncovered_warning(&[]), None);
  }
}
